name: haskell-nix-minimal

dependencies:
  - bson
library:
  source-dirs: library
_executable: &executable
  ghc-options:
    - -rtsopts
    - -threaded
  main: Main.hs
executable:
  <<: *executable
  dependencies: haskell-nix-minimal
  source-dirs: executable
