name: haskell-nix-minimal
version: 22
default-extensions:
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables

dependencies:
  - aeson
  - aeson-qq
  - amazonka
  - amazonka-cloudwatch
  - amazonka-cloudwatch-events
  - amazonka-core
  - amazonka-s3
  - amazonka-sns
  - amazonka-sqs
  - amazonka-sts
  - async
  - base
  - base64-bytestring
  - bcrypt
  - bson
  - bytestring
  - case-insensitive
  - cassava
  - clock
  - conduit
  - conduit-combinators
  - containers
  - convertible
  - cryptonite
  - csv-conduit
  - deepseq
  - directory
  - dlist
  - either
  - email-validate
  - envy
  - exceptions
  - extra
  - filepath
  - happstack-server
  - hashable
  - HDBC
  - HDBC-postgresql
  - hedis
  - hslogger
  - http-client
  - http-client-tls
  - http-conduit
  - http-types
  - JuicyPixels
  - JuicyPixels-extra
  - jwt
  - lens
  - memory
  - monad-control
  - mongoDB
  - mono-traversable
  - mtl
  - network
  - network-uri
  - orville
  - parsec
  - random
  - resource-pool
  - resourcet
  - scientific
  - split
  - stm
  - template-haskell
  - text
  - time
  - transformers
  - transformers-base
  - unliftio-core
  - unordered-containers
  - uuid
  - vector
  - xml-conduit
  - xml-conduit-writer
  - xml-lens
  - xml-types
ghc-options:
  - -Weverything
  - -Wno-all-missed-specializations
  - -Wno-implicit-prelude
  - -Wno-missed-specialisations
  - -Wno-missing-deriving-strategies
  - -Wno-missing-exported-signatures
  - -Wno-safe
  - -Wno-unsafe
extra-source-files:
  - .hlint.yaml
  - brittany.yaml
data-dir: data
data-files:
  - border.jpg
  - logo.jpg
  - signature.jpg
library:
  source-dirs: library
_executable: &executable
  ghc-options:
    - -rtsopts
    - -threaded
  main: Main.hs
executable:
  <<: *executable
  dependencies: haskell-nix-minimal
  source-dirs: executable
