name: haskell-nix-minimal
version: 23

dependencies:
  - HDBC-postgresql


library:
  source-dirs: library

_executable: &executable
  main: Main.hs

executable:
  ghc-options:
    - -rtsopts
    - -threaded
  dependencies: haskell-nix-minimal
  source-dirs: executable
  main: Main.hs