name: haskell-nix-minimal
version: 22
default-extensions:
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables

dependencies:
  - base >= 4.7 && < 5
  - stm
ghc-options:
  - -Weverything
  - -Wno-all-missed-specializations
  - -Wno-implicit-prelude
  - -Wno-missed-specialisations
  - -Wno-missing-deriving-strategies
  - -Wno-missing-exported-signatures
  - -Wno-safe
  - -Wno-unsafe
extra-source-files:
  - .hlint.yaml
  - brittany.yaml
data-dir: data
data-files:
  - border.jpg
  - logo.jpg
  - signature.jpg
library:
  source-dirs: library
_executable: &executable
  ghc-options:
    - -rtsopts
    - -threaded
  main: Main.hs
executable:
  <<: *executable
  dependencies: haskell-nix-minimal
  source-dirs: executable
