allow-different-user: true

resolver: lts-16.6

# always disable stack nix integration, even on nix
# Our nix-shell is an environment that provides stack with
# the correct GHC_PKG_PATH
nix:
  enable: false
# Use the nix installed ghc
system-ghc: true
install-ghc: true

extra-deps:
  - AesonBson-0.4.0
  - happstack-server-7.6.0
  - HDBC-postgresql-2.3.2.7
  - json-0.10

  # We have our own custom orville package that we forked from flipstone:
  # https://github.com/flipstone/orville
  - git: https://github.com/EdutainmentLIVE/orville
    commit: 8a2432891e96a547777b67a67135e235a1dce80c
    # nix-sha256: 0i8z3zr4z55bzidlh3pz3r3h0hachk5ndfhznw3kqk4c5j6y27ry

  # These packages require patches that aren't yet available on Hackage. We're
  # required to pull them from GitHub instead. If you add a package here, be
  # sure to include a link to an upstream pull request. Once the pull request
  # is merged and released to Hackage, we can stop using the GitHub source.

  # <https://github.com/hdbc/convertible/pull/15>
  - git: https://github.com/codygman/convertible
    commit: 9e4849e143458aa3175e71bc2a8a29502272eb88
    # nix-sha256: 1v6a2gsv9am0j4vs9gdxar8fadzrlnf6qqf6wwnk87d7jflhjhw3

  # <https://github.com/hsyl20/HPDF/pull/1>
  - git: https://github.com/aschmois/HPDF
    commit: 33097b1485062f0c1cbe0b97bc26eb1a27385dbf
    # nix-sha256: 153qijffd4sjr9jhl0l0d3gzjsplfvzpy0ip0v4y0dg6pla20vmq