allow-different-user: true

resolver: lts-16.6

# always disable stack nix integration, even on nix
# Our nix-shell is an environment that provides stack with
# the correct GHC_PKG_PATH
nix:
  enable: false
# Use the nix installed ghc
system-ghc: true
install-ghc: true

extra-deps:
  - HDBC-postgresql-2.3.2.7