allow-different-user: true
resolver: nightly-2020-01-08
extra-deps:
  - happstack-server-7.6.0
  - HDBC-2.4.0.3
  - HDBC-postgresql-2.3.2.7
  - hedis-0.12.9
  - hslogger-1.3.1.0
  - HTTP-4000.3.14
  - mongoDB-2.6.0.0
  - xml-lens-0.2

  # <https://github.com/GaloisInc/json/pull/9>
  - git: https://github.com/quasicomputational/json
    commit: e867c442687f267dc1cc41a3492405b1ec5ab9e6

  # <https://github.com/haskell/network-bsd/pull/4>
  - git: https://github.com/haskell-vanguard/network-bsd
    commit: 9f372485748f8b29ce6e723eb838da6f55d4157f

flags:
  bson:
    _old-network: false # <https://github.com/mongodb-haskell/bson/pull/18>
  mongoDB:
    _old-network: false # <https://github.com/mongodb-haskell/mongodb/pull/98>
